apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: falco-remediation-netpol
  namespace: security-monitoring
spec:
  podSelector:
    matchLabels:
      app: falco-remediation
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: security-monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: falco
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # Zero-Trust & Strict Least Privilege:
    # InClusterConfig() pod enjekte env (KUBERNETES_SERVICE_HOST) uzerinden IP ile baglanir.
    # DNS (port 53) ve Dis Dunya (0.0.0.0/0) tamamen engellenmistir.
    - to:
        - ipBlock:
            cidr: 10.96.0.1/32
      ports:
        - protocol: TCP
          port: 443
