apiVersion: v1
kind: Namespace
metadata:
  name: security-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-remediation-sa
  namespace: security-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-remediation-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco-remediation-binding
subjects:
  - kind: ServiceAccount
    name: falco-remediation-sa
    namespace: security-monitoring
roleRef:
  kind: ClusterRole
  name: falco-remediation-role
  apiGroup: rbac.authorization.k8s.io
