apiVersion: v1
kind: Namespace
metadata:
  name: security-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-remediation-sa
  namespace: security-monitoring
---
# Least-Privilege: ClusterRole YERINE Namespace-Scoped Role
# Saldırgan worker'ı ele geçirse bile diğer namespace'lerdeki pod'lara dokunamaz!
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: falco-remediation-role
  namespace: fintech-gateway
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: falco-remediation-binding
  namespace: fintech-gateway
subjects:
  - kind: ServiceAccount
    name: falco-remediation-sa
    namespace: security-monitoring
roleRef:
  kind: Role
  name: falco-remediation-role
  apiGroup: rbac.authorization.k8s.io
