apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardened-workload
  namespace: fintech-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardened
  template:
    metadata:
      labels:
        app: hardened
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          # CRITICAL FIX: Immutable SHA256 yerine ":latest" kullanımı yasaktır.
          image: cgr.dev/chainguard/static@sha256:d8a29a4128f729fcc01a35a6039543940be66d863f6e8d24b61ff6cc7c132890
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
